### ISSUE TITLE
cant build 

### ISSUE THREAD

**Issue by mhtranbn** [liyanhuadev/ObjectMapper-Plugin#2]
need mac sign

**Comment by liyanhuadev** [comment]
use your apple developer account

**Comment by mhtranbn** [comment]
cant build by my apple id account, @liyanhuadev  can you help me, many thanks for you.

**Comment by mhtranbn** [comment]
Each time use it need run project ObjectMapper-Plugin to get excommand?

**Comment by liyanhuadev** [comment]
1、XCode Menu - Product -Archive
2、Export - Export as a masOS App
3、Install it 
i use this way, it work for me

**Comment by amiv1** [comment]
@liyanhuadev Hi. I'm trying to build and install this plugin for XCode as per your steps but "ExCommand" option in the Editor menu doesn't show up. I'm completely new to Mac OS X and iOS development and it's unclear how to enable and use this. Is it enough to drag exported **.app** file into the Applications folder? Because it doesn't seem to be the case.

**Comment by HardikDG** [comment]
How to install it? 
I have exported it as MacOS app. when I click it It is opening blank screen with the app window. What should I do to install the Plugin in the xcode?
